shop/products/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', IndexView.as_view() , name='index'),
    url(r'^product/id(?P<sku_id>\d+)/$', ProductView.as_view(), name='product'),
    url(r'^favourites/$', FavouritesView.as_view(), name='favourites'),
    url(r'^search/', SearchView.as_view(), name='search'),
    url(r'^like/', LikeUpdate.as_view(), name='like_action'),
    url(r'^add_comment/(?P<sku_id>\d+)/$', CommentCreate.as_view(), name='add_comment'),
    url(r'^buy/id(?P<sku_id>\d+)/c(?P<cost>\d+)/$', Payment.as_view(), name='buy'),
]

shop/shop/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from shop import settings
import loginsys.urls
import products.urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include(loginsys.urls)),
    url(r'^', include(products.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/products/models.py
from django.db import models
from django.db.models import Q
from django.dispatch import receiver
from django.db.models.signals import m2m_changed
from mptt.models import MPTTModel, TreeForeignKey
from urllib.parse import urlencode, urlunsplit
from datetime import datetime
from .storage import OverwriteStorage
from re import sub
import os
import re


def get_upload_path(instance, filename):
    file_type = filename.split('.')[-1]
    return os.path.join(datetime.now().date().strftime('%Y/%m/%d'),
                        '{}.{}'.format(sub(r'\s|\.', '', instance.stock_id), file_type))


def search_sku_by_regex(string):
    only_fields = ['name', 'manufacturer__name']
    products = list(Product.objects.select_related().only(*only_fields))

    strings = string.split(' ')
    print(strings)

    for s in strings:
        products = list(filter(lambda x: re.search(s, x.manufacturer.name + ' ' + x.name, re.IGNORECASE), products))

    skus = SKU.objects.filter(product__in=products)
    return skus


class Manufacturer(models.Model):
    class Meta:
        verbose_name_plural = 'Manufacturers'

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Category(MPTTModel):
    class Meta:
        verbose_name_plural = 'Categories'

    class MPTTMeta:
        order_insertion_by = ['name']

    name = models.CharField(max_length=100, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='subcategories')

    def get_url(self):
        query = {'cat': self.name}
        query_string = urlencode(query)
        return urlunsplit(('', '', '/search', query_string, ''))

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name_plural = 'Products'

    OS_CHOICES = (
        ('win7', 'Windows 7'),
        ('win8', 'Windows 8'),
        ('win10', 'Windows 10'),
        ('lin', 'Linux'),
        ('mcos', 'Mac OS X'),
        ('ios', 'iOS'),
        ('and', 'Android'),
        ('winp', 'Windows phone'),
        ('blckb', 'Blackberry OS'),
        ('wtch', 'Watch OS')
        # ...
    )

    BATTERY_TYPE = (
        ('lipol', 'Li-Pol'),
        ('liion', 'Li-Ion'),
        ('nicd', 'Ni-Cd'),
        ('nimh', 'Ni-MH'),
    )

    name = models.CharField(max_length=100)
    description = models.TextField()
    manufacturer = models.ForeignKey(Manufacturer, related_name='products')
    categories = models.ManyToManyField(Category, related_name='products')

    os_type = models.CharField(max_length=50, choices=OS_CHOICES, null=True, blank=True)
    battery_type = models.CharField(max_length=50, choices=BATTERY_TYPE, default=None, null=True, blank=True)
    processor = models.CharField(max_length=50, default=None, null=True, blank=True)
    connectors = models.CharField(max_length=100, default=None, blank=True, null=True)

    creation_year = models.IntegerField(default=None, null=True, blank=True)
    cores_count = models.IntegerField(default=None, null=True, blank=True)
    camera = models.IntegerField(default=None, null=True, blank=True, help_text='In mega pixels')
    ram = models.IntegerField(default=None, null=True, blank=True, help_text='In gigabytes')
    builtin_memory = models.IntegerField(default=None, null=True, blank=True, help_text='In gigabytes')

    has_bluetooth = models.BooleanField(default=False)
    has_wifi = models.BooleanField(default=False)

    def fullname(self):
        return '{} {}'.format(self.manufacturer.name, self.name)

    def __str__(self):
        return self.name


@receiver(m2m_changed, sender=Product.categories.through)
def update_product_categories(sender, instance, **kwargs):
    action = kwargs.pop('action', None)

    if action == 'post_add' or action == 'post_remove':
        for category in instance.categories.all():
            for ancestor in category.get_ancestors():
                if ancestor not in instance.categories.all():
                    instance.categories.add(ancestor)


class Batch(models.Model):
    class Meta:
        verbose_name_plural = 'Batches'

    cost = models.IntegerField()
    count = models.IntegerField()

    def __str__(self):
        return '{}$ - {}'.format(self.cost, self.count)


class SKU(models.Model):
    class Meta:
        verbose_name_plural = 'SKUs'

    COLOR_CHOICES = (
        ('bk', 'Black'),
        ('bn', 'Brown'),
        ('be', 'Blue'),
        ('yw', 'Yellow'),
        ('rd', 'Red'),
        ('pk', 'Pink'),
        ('pe', 'Purple'),
        ('gn', 'Green'),
        ('we', 'White'),
        ('gy', 'Gray'),
        ('oe', 'Orange'),
    )

    MATERIAL_CHOICES = (
        ('pc', 'Polycarbonate'),
        ('al', 'Aluminum'),
        ('st', 'Steel'),
        ('gl', 'Glass'),
    )

    color = models.CharField(max_length=50, choices=COLOR_CHOICES)
    screen_diagonal = models.FloatField()
    screen_resolution = models.CharField(max_length=50, null=True, blank=True, help_text='Format: 640x480')
    body_material = models.CharField(max_length=50, choices=MATERIAL_CHOICES)
    weight = models.IntegerField(help_text='In grams')
    battery_capacity = models.IntegerField(default=None, null=True, blank=True, help_text='In Milliamp * hour')

    likes = models.IntegerField(default=0)
    stock_id = models.CharField(max_length=50, unique=True)
    product = models.ForeignKey(Product, related_name='skus')
    image = models.ImageField(storage=OverwriteStorage(), upload_to=get_upload_path)
    batch = models.OneToOneField(Batch, related_name='sku')

    def get_batch_status(self):
        try:
            x = self.batch
            return 1
        except:
            return 0

    def get_ppi(self):
        if self.screen_resolution:
            w, h = map(int, self.screen_resolution.split('x'))
            diagonal_in_px = (w ** 2 + h ** 2) ** 0.5
            return int(diagonal_in_px / self.screen_diagonal)

        return None

    def save(self, *args, **kwargs):
        self.stock_id = '{}  {}{}{}{}{}'.format(self.product.name, self.color, self.body_material,
                                                str(self.screen_diagonal), self.screen_resolution,
                                                str(self.weight))
        super(SKU, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.image.delete()
        super(SKU, self).delete(*args, **kwargs)

    def __str__(self):
        return self.stock_id


from loginsys.models import UserProfile


class Comment(models.Model):
    class Meta:
        verbose_name_plural = 'Comments'

    owner = models.ForeignKey(UserProfile, related_name='comments')
    time = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    sku = models.ForeignKey(SKU, related_name='comments')

    def __str__(self):
        return self.content

shop/products/views.py
from django.shortcuts import render, redirect, HttpResponse, Http404
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.template .context_processors import csrf
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from ratelimit.decorators import ratelimit
from .models import *
import json


class IndexView(ListView):
    model = SKU
    context_object_name = 'skus'
    template_name = 'products/index.html'
    paginate_by = 8


    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['nodes'] = Category.objects.all()
        context['can_search'] = True
        return context


    def get_queryset(self):
        only_fields = ['product__name', 'product__manufacturer__name', 'batch',]
        queryset = self.model.objects.select_related().only(*only_fields).order_by('-batch__count', '-likes')
        return queryset


class FavouritesView(LoginRequiredMixin, ListView):
    model = SKU
    context_object_name = 'liked_skus'
    template_name = 'products/favourites.html'
    paginate_by = 12


    def get_context_data(self, **kwargs):
        context = super(FavouritesView, self).get_context_data(**kwargs)
        context['can_search'] = True
        context['is_empty'] = not bool(context[self.context_object_name].count())
        return context


    def get_queryset(self):
        user_profile = UserProfile.objects.get(user__id=self.request.user.id)

        only_fields = ['product__name', 'product__manufacturer__name', 'batch',]
        queryset = user_profile.favourites.select_related().only(*only_fields)
        return queryset


class SearchView(ListView):
    model = SKU
    context_object_name = 'skus'
    template_name = 'products/search.html'

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            self.object_list = self.get_queryset()
            context = self.get_context_data_for_ajax()
            html = render_to_string('products/includes/search-div.html', context)
            return HttpResponse(html)

        return super(SearchView, self).get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['can_search'] = True
        context['categories'] = Category.objects.only('name').order_by('level')
        context['manufacturers'] = Manufacturer.objects.only('name').order_by('name')
        context['is_empty'] = not bool(context[self.context_object_name].count())
        context['colors'] = sorted([x[1] for x in SKU.COLOR_CHOICES])
        context['expr'] = self.get_expr()
        return context


    def get_context_data_for_ajax(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['is_empty'] = not bool(context[self.context_object_name].count())
        context['expr'] = self.get_expr()
        return context


    def get_queryset(self):
        only_fields = ['product__name', 'product__manufacturer__name', 'batch',]
        queryset = self.model.objects.select_related().only(*only_fields)

        try:
            if 'cat' in self.request.GET:
                category = self.request.GET['cat']
                queryset = queryset.filter(product__in=Category.objects.get(name=category).products.only('id'))

            if 'clrs' in self.request.GET:
                colors = json.loads(self.request.GET['clrs'])
                queryset = queryset.filter(color__in=colors)

            if 'manufs' in self.request.GET:
                manufacturers = json.loads(self.request.GET['manufs'])
                queryset = queryset.filter(product__manufacturer__name__in=manufacturers)

            if 'has_wifi' in self.request.GET:
                if self.request.GET['has_wifi']:
                    queryset = queryset.filter(product__has_wifi=True)

            if 'has_bluetooth' in self.request.GET:
                if self.request.GET['has_bluetooth']:
                    queryset = queryset.filter(product__has_bluetooth=True)

            if 'expr' in self.request.GET:
                string = self.get_expr()
                strings = string.split(' ')

                skus = list(queryset)

                for s in strings:
                    skus = list(filter(lambda x: re.search(s, x.product.manufacturer.name +
                                                           ' ' + x.product.name, re.IGNORECASE), skus))

                ids = map(lambda x: x.id, skus)
                queryset = SKU.objects.filter(id__in=ids)
        except:
            queryset = self.model.objects.none()

        return queryset.order_by('-batch__count', '-likes')


    def get_expr(self):
        return self.request.GET.get('expr', None)


    @method_decorator(ratelimit(key='ip', rate='5/s', block=True))
    def dispatch(self, request, *args, **kwargs):
        return super(SearchView, self).dispatch(request, *args, **kwargs)


class ProductView(DetailView):
    model = SKU
    context_object_name = 'sku'
    template_name = 'products/product.html'


    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context['can_search'] = False
        context['product'] = self.object.product
        context['comments'] = self.object.comments.select_related().only('owner__user__username').order_by('-time')
        context['is_liked'] = self.is_liked_product()
        context['batch'] = self.object.batch
        return context


    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        try:
            sku_id = self.kwargs['sku_id']
            obj = queryset.get(id=sku_id)
        except:
            raise Http404()

        return obj


    def is_liked_product(self):
        try:
            user_profile = UserProfile.objects.get(user__id=self.request.user.id)
            return bool(user_profile.favourites.filter(id=self.kwargs['sku_id']))
        except:
            return False


class LikeUpdate(LoginRequiredMixin, UpdateView):
    http_method_names = ['get']
    template_name = 'products/includes/btns.html'


    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            sku_id = int(request.GET['id'])
            sku = SKU.objects.get(id=sku_id)

            action = request.GET['action']
            status = self.get_action_status(action, sku_id)
            batch = sku.batch
            product = sku.product

            context = {'is_liked': status, 'batch': batch, 'product': product}
            html = render_to_string(self.template_name, context)
            return HttpResponse(html)

        raise Http404()


    def get_action_status(self, action, sku_id):
        user_profile = UserProfile.objects.get(user__id=self.request.user.id)
        sku = SKU.objects.get(id=sku_id)
        result = True

        if action == 'lk':
            sku.likes = sku.likes + 1
            user_profile.favourites.add(sku_id)
        else:
            sku.likes = sku.likes - 1
            user_profile.favourites.remove(sku_id)
            result = False

        sku.save()
        user_profile.save()
        return result


    def http_method_not_allowed(self, request, *args, **kwargs):
        raise Http404()


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    context_object_name = 'comments'
    http_method_names = ['post']
    template_name = 'products/includes/comments.html'
    fields = ['content']


    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            text = request.POST['content']
            sku_id = int(self.kwargs['sku_id'])

            self.create_comment(text, sku_id)

            html = render_to_string(self.template_name, self.get_context_data())
            return HttpResponse(html)

        raise Http404()


    def create_comment(self, text, sku_id):
        user_profile = UserProfile.objects.only('id').get(user__id=self.request.user.id)
        self.sku = SKU.objects.get(id=sku_id)
        self.sku.comments.create(owner=user_profile, content=text)


    def get_context_data(self, **kwargs):
        context ={self.context_object_name: self.get_queryset()}
        return context


    def get_queryset(self):
        only_fields = ['owner__user__username']
        queryset = self.sku.comments.select_related().only(*only_fields).order_by('-time')
        return queryset


    def http_method_not_allowed(self, request, *args, **kwargs):
        raise Http404()


    @method_decorator(ratelimit(key='user', rate='5/m', block=True))
    def dispatch(self, request, *args, **kwargs):
        return super(CommentCreate, self).dispatch(request, *args, **kwargs)


class Payment(LoginRequiredMixin, View):
    http_method_names = ['post',]

    # UPDATE
    def post(self, request, *args, **kwargs):
        prev_cost = int(self.kwargs['cost'])
        sku_id = self.kwargs['sku_id']
        batch = SKU.objects.get(id=sku_id).batch

        if batch.count == 0:
            print('no products')
        elif prev_cost != batch.cost:
            print('product cost changed')
        else:
            batch.count = batch.count - 1
            batch.save()

        redirect_url = '/product/id' + sku_id
        return redirect(redirect_url)


    def http_method_not_allowed(self, request, *args, **kwargs):
        raise Http404()

shop/products/templates/products/favourites.html
{% extends 'main/base.html' %}


{% block title %}Liked{% endblock %}


{% block navbar-lis %}
    <li><a href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a></li>
    <li class="active"><a href="{% url 'favourites' %}">Liked</a></li>
    <li id="last-li"><a href="{% url 'logout' %}">Logout</a></li>
{% endblock %}


{% block body %}

    <div id="index-main" class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">

        <h3 class="text-center caption font-big">Liked products</h3>

        <div class="row">
            {% if is_empty %}
                <p class="text-center font-mid message">You do not have liked products</p>
            {% else %}
                {% for sku in liked_skus %}
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <a class="no-dec" href="{% url 'product' sku.id %}">
                            <div class="thumbnail shadow">
                                <img class="img-responsive" src="{{ MEDIA_URL }}{{ sku.image }}" alt="img">

                                <div class="caption product">
                                    <p class="text-center product-name font-mid"><b>{{ sku.product.manufacturer.name }}</b></p>
                                    <p class="text-center product-name font-mid"><b>{{ sku.product.name }}</b></p>
                                    <hr class="product-hr">

                                    <h4 class="text-center cost-text font-mid"><b>${{ sku.batch.cost }}</b></h4>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        {% if is_paginated %}
            <center>
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li class="page-item">
                            {% if page_obj.has_previous %}
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            {% else %}
                                <a class="disabled page-link" href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            {% endif %}
                        </li>

                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                <li class="active page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}


                        <li class="page-item">
                            {% if page_obj.has_next %}
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            {% else %}
                                <a class="disabled page-link" href="" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
            </center>
        {% endif %}
    </div>

{% endblock %}

shop/products/templates/products/product.html
{% extends 'main/base.html' %}
{% load staticfiles %}


{% block title %}{{ product.manufacturer }} {{ product.name }}{% endblock %}


{% block navbar-lis %}
	{% if user.is_authenticated %}
		<!--suppress ALL -->
		<li><a href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a></li>
		<li><a href="{% url 'favourites' %}">Liked</a></li>
		<li id="last-li"><a href="{% url 'logout' %}">Logout</a></li>
	{% else %}
		<li><a href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a></li>
		<li><a href="{% url 'login' %}">Login</a></li>
		<li id="last-li"><a href="{% url 'register' %}">Register</a></li>
	{% endif %}
{% endblock%}


{% block body %}
		<div id="product-div" class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">
			<!--photo-->
			<div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
				<div id="image" class="thumbnail">
					<img class="img-responsive" id="product-image" src="{{ MEDIA_URL }}{{ sku.image }}" alt="img">
				</div>
			</div>

			<!-- description -->
			<div id="description" class="col-xs-12 col-sm-7 col-md-8 col-lg-8 col-lg-offset-1">
				<div class="caption-full">
						<div class="row">
	                        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
	                        	<h3 id="product-name" class="font-big"><b>{{ product.manufacturer }} {{ product.name }}</b></h3>
	                        </div>

							<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 text-right">
								<h3 class="font-big product-cost"><b>${{ batch.cost }}</b></h3>
							</div>
                        </div>

                        <center>
	                        <div id="product-categories-div">
								{% for category in product.categories.all %}
									{% if category.level == 0 %}
										<a href="{{ category.get_url }}"><button type="button" class="btn btn-success product-categories font-small">{{ category.name }}</button></a>
									{% elif category.level == 1 %}
										<a href="{{ category.get_url }}"><button type="button" class="btn btn-info product-categories font-small">{{ category.name }}</button></a>
									{% elif category.level == 2 %}
										<a href="{{ category.get_url }}"><button type="button" class="btn btn-warning product-categories font-small">{{ category.name }}</button></a>
									{% else %}
										<a href="{{ category.get_url }}"><button type="button" class="btn btn-default product-categories font-small">{{ category.name }}</button></a>
									{% endif %}
								{% endfor %}
	                        </div>
                        </center>

                        <p class="font-small">{{ product.description }}</p>
                </div>
			</div>


			<div id="info" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<hr class="product-hr">

				<p class="font-big text-center"><i>Information</i></p>

				<div class="row text-left">
					<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 font-mid">
						<p class="no-margin font-mid"><b id="owner">Manufacturer: </b><a href='/search/?manufs=["{{ product.manufacturer.name }}"]'>{{ product.manufacturer.name }}</a></p>

						{% if batch.count %}
							<p class="no-margin font-mid"><b id="phone">In store: </b>{{ batch.count }}</p>
						{% else %}
							<p class="no-margin font-mid"><b id="phone">In store: </b>-</p>
						{% endif %}
					</div>


					<div id="product-buttons" class="col-xs-12 col-sm-4 col-md-4 col-lg-4 text-right">
                        {% if user.is_authenticated %}
							<div id="btns">
								{% include 'products/includes/btns.html' %}
							</div>
						{% endif %}
					</div>
				</div>
			</div>


			<div id="characteristics" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<hr class="product-hr">


				<table class="font-small table table-striped">
				  	<tbody>
				    	<tr>
				      		<th class="col-xs-6 col-sm-6 col-md-6 col-lg-6" scope="row">Color</th>
				      		<td>{{ sku.get_color_display }}</td>
				    	</tr>


				    	<tr>
				      		<th class="col-xs-6 col-sm-6 col-md-6 col-lg-6" scope="row">Body material</th>
				      		<td>{{ sku.get_body_material_display }}</td>
						</tr>


						{% if product.os_type %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-6 col-lg-6" scope="row">Operational system</th>
						  	<td>{{ product.get_os_type_display }}</td>
						</tr>
						{% endif %}


						{% if product.creation_year %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Creation year</th>
						  	<td>{{ product.creation_year }}</td>
						</tr>
						{% endif %}


						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Weight</th>
						  	<td>{{ sku.weight }} grams</td>
						</tr>


						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Screen diagonal</th>
						  	<td>{{ sku.screen_diagonal }}"</td>
						</tr>


						{% if sku.screen_resolution %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Screen resolution</th>
						  	<td>{{ sku.screen_resolution }}</td>
						</tr>
						{% endif %}


						{% if sku.get_ppi %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Pixels per inch</th>
						  	<td>{{ sku.get_ppi }}</td>
						</tr>
						{% endif %}


						{% if product.camera %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Camera</th>
						  	<td>{{ product.camera }} megapixels</td>
						</tr>
						{% endif %}


						{% if product.processor %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Processor</th>
						  	<td>{{ product.processor }}</td>
						</tr>
						{% endif %}


						{% if product.cores_count %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Cores count</th>
						  	<td>{{ product.cores_count }}</td>
						</tr>
						{% endif %}


						{% if product.ram %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">RAM</th>
						  	<td>{{ product.ram }} gigabytes</td>
						</tr>
						{% endif %}


						{% if product.builtin_memory %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Built-in memory</th>
						  	<td>{{ product.builtin_memory }} gigabytes</td>
						</tr>
						{% endif %}


						{% if product.battery_type %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Battery type</th>
						  	<td>{{ product.get_battery_type_display }}</td>
						</tr>
						{% endif %}


						{% if sku.battery_capacity %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Battery capacity</th>
						  	<td>{{ sku.battery_capacity }} milliamp * hour</td>
						</tr>
						{% endif %}


						{% if product.connectors %}
						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Connectors</th>
						  	<td>{{ product.connectors }}</td>
						</tr>
						{% endif %}


						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Wifi</th>

							{% if product.has_wifi %}
						  		<td>Yes</td>
							{% else %}
								<td>No</td>
							{% endif %}
						</tr>


						<tr>
						  	<th class="col-xs-6 col-sm-6 col-md-4 col-lg-4" scope="row">Bluetooth</th>

							{% if product.has_bluetooth %}
						  		<td>Yes</td>
							{% else %}
								<td>No</td>
							{% endif %}
						</tr>
				  	</tbody>
				</table>
			</div>


			<div id="comments" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<hr class="product-hr">

				<p class="font-big text-center"><i>Comments</i></p>

				{% if user.is_authenticated %}
					<div id="add-comment" class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
						<form>
							{% csrf_token %}
							<center>
								<div id="comment" class="form-group">
									<textarea required class="form-control font-small" name="content" id="comment-content" rows="3"></textarea>
								</div>

								<input id="btn-comment" class="btn btn-primary btn-block font-mid" value="Add comment" type="submit"/>
							</center>
						</form>
					</div>
				{% endif %}

				<div id="cmnts">
					{% include 'products/includes/comments.html' %}
				</div>
			</div>
		</div>

{% endblock %}


{% block scripts %}
	<script src="{% static 'admin/js/bootbox.min.js' %}"></script>
	<script src="{% static 'products/js/payment.js' %}"></script>
	<script src="{% static 'products/js/like-ajax.js' %}"></script>
	<script src="{% static 'products/js/comment-ajax.js' %}"></script>
{% endblock %}